name: Ansible Lint

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-python@v1
      with:
        python-version: '3.x'
        architecture: 'x64'
    - run: pip install ansible ansible-lint
    - name: Syntax Check
      run: ansible-playbook -i inventory --syntax-check main.yml
    - name: Ansible Lint
      run: ansible-lint -v **/*

